# Generated by Django 3.1.2 on 2020-11-08 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0003_add_role_class'),
        ('authtest', '0002_remove_user_type'),
    ]

    operations = [
    ]
