# Generated by Django 3.1.2 on 2020-11-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtest', '0007_auto_20201108_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
